import type {Entry} from '../lib/budget';
let root:string|null=null;
async function storageRoot(){if(root)return root;const r=await fetch('./firebase-config.json',{cache:'no-store'});if(!r.ok)throw Error('Le projet Firebase carnet-dépenses reste à connecter.');const config=await r.json() as {projectId?:string};if(!config.projectId || !/^[a-z][a-z0-9-]{4,28}[a-z0-9]$/.test(config.projectId))throw Error('Le projet Firebase carnet-dépenses reste à connecter.');root='https://firestore.googleapis.com/v1/projects/'+config.projectId+'/databases/(default)/documents/expenseVaultsV1/';return root;}
let secret='',key:CryptoKey|null=null,version:string|null=null;
const encode=(b:Uint8Array)=>btoa(Array.from(b,x=>String.fromCharCode(x)).join(''));
const decode=(s:string)=>Uint8Array.from(atob(s),x=>x.charCodeAt(0));
function accessCode(){const fragment=new URLSearchParams(location.hash.slice(1)).get('carnet');const saved=localStorage.getItem('budget-access-code');const candidate=fragment||saved||'';if(!/^[a-f0-9]{64}$/.test(candidate))throw Error('Ouvre ton lien personnel ou saisis ton code pour accéder au carnet.');return candidate;}
async function ready(){if(key)return;secret=accessCode();key=await crypto.subtle.importKey('raw',Uint8Array.from(secret.match(/../g)!,x=>parseInt(x,16)),{name:'AES-GCM'},false,['encrypt','decrypt']);localStorage.setItem('budget-access-code',secret);}
async function documentURL(){await ready();const digest=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(secret)));return (await storageRoot())+Array.from(digest,b=>b.toString(16).padStart(2,'0')).join('');}
export async function readEntries():Promise<Entry[]>{const url=await documentURL();const r=await fetch(url,{cache:'no-store'});if(r.status===404){version=null;return [];}if(!r.ok)throw Error('La sauvegarde est indisponible. Réessaie dans un instant.');const d=await r.json() as {fields:{iv:{stringValue:string};ciphertext:{stringValue:string}},updateTime:string};try{const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:decode(d.fields.iv.stringValue)},key!,decode(d.fields.ciphertext.stringValue));const entries=JSON.parse(new TextDecoder().decode(raw));if(!Array.isArray(entries))throw Error('Invalid data');version=d.updateTime;return entries;}catch{throw Error('Ce code ne permet pas d’ouvrir le carnet ou la sauvegarde est endommagée.');}}
async function writeEntries(entries:Entry[]){const url=await documentURL();const iv=crypto.getRandomValues(new Uint8Array(12));const bytes=await crypto.subtle.encrypt({name:'AES-GCM',iv},key!,new TextEncoder().encode(JSON.stringify(entries)));const query=version?'?currentDocument.updateTime='+encodeURIComponent(version):'?currentDocument.exists=false';const r=await fetch(url+query,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({fields:{format:{integerValue:'1'},iv:{stringValue:encode(iv)},ciphertext:{stringValue:encode(new Uint8Array(bytes))}}})});if(r.status===409||r.status===412||r.status===400)throw Error('Le carnet a changé sur un autre appareil. Recharge les données avant de réessayer.');if(!r.ok)throw Error('Enregistrement impossible. Ton formulaire est conservé.');version=(await r.json() as {updateTime:string}).updateTime;}
export async function saveEntry(e:Entry){const entries=await readEntries();const i=entries.findIndex(x=>x.id===e.id);if(i<0)entries.push(e);else entries[i]=e;await writeEntries(entries);}
export async function deleteEntry(id:string){const entries=await readEntries();await writeEntries(entries.filter(e=>e.id!==id));}
export function unlock(code:string){if(!/^[a-f0-9]{64}$/.test(code.trim()))throw Error('Le code doit contenir 64 caractères.');localStorage.setItem('budget-access-code',code.trim());location.hash='carnet='+code.trim();location.reload();}
export function createNotebook(){const code=Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');unlock(code);}
export function hasAccess(){try{accessCode();return true;}catch{return false;}}
export function personalLink(){return location.origin+location.pathname+'#carnet='+accessCode();}
